export const heresCapsuleManagerAbi = [
  {
    type: 'function',
    name: 'nextCapsuleId',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'createCapsule',
    stateMutability: 'payable',
    inputs: [
      { name: 'beneficiary', type: 'address' },
      { name: 'conditionKind', type: 'uint8' },
      { name: 'executeAt', type: 'uint64' },
      { name: 'heartbeatWindow', type: 'uint64' },
      { name: 'metadataHash', type: 'bytes32' },
    ],
    outputs: [{ name: 'capsuleId', type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'heartbeat',
    stateMutability: 'nonpayable',
    inputs: [{ name: 'capsuleId', type: 'uint256' }],
    outputs: [],
  },
  {
    type: 'function',
    name: 'executeCapsule',
    stateMutability: 'nonpayable',
    inputs: [{ name: 'capsuleId', type: 'uint256' }],
    outputs: [],
  },
  {
    type: 'function',
    name: 'cancelCapsule',
    stateMutability: 'nonpayable',
    inputs: [{ name: 'capsuleId', type: 'uint256' }],
    outputs: [],
  },
  {
    type: 'function',
    name: 'getCapsule',
    stateMutability: 'view',
    inputs: [{ name: 'capsuleId', type: 'uint256' }],
    outputs: [
      {
        type: 'tuple',
        components: [
          { name: 'owner', type: 'address' },
          { name: 'beneficiary', type: 'address' },
          { name: 'amount', type: 'uint256' },
          { name: 'createdAt', type: 'uint64' },
          { name: 'executeAt', type: 'uint64' },
          { name: 'heartbeatWindow', type: 'uint64' },
          { name: 'lastHeartbeatAt', type: 'uint64' },
          { name: 'metadataHash', type: 'bytes32' },
          { name: 'conditionKind', type: 'uint8' },
          { name: 'executed', type: 'bool' },
          { name: 'cancelled', type: 'bool' },
        ],
      },
    ],
  },
  {
    type: 'function',
    name: 'canExecute',
    stateMutability: 'view',
    inputs: [{ name: 'capsuleId', type: 'uint256' }],
    outputs: [{ name: '', type: 'bool' }],
  },
  {
    type: 'event',
    name: 'CapsuleCreated',
    anonymous: false,
    inputs: [
      { indexed: true, name: 'capsuleId', type: 'uint256' },
      { indexed: true, name: 'owner', type: 'address' },
      { indexed: true, name: 'beneficiary', type: 'address' },
      { indexed: false, name: 'amount', type: 'uint256' },
      { indexed: false, name: 'conditionKind', type: 'uint8' },
      { indexed: false, name: 'executeAt', type: 'uint64' },
      { indexed: false, name: 'heartbeatWindow', type: 'uint64' },
      { indexed: false, name: 'metadataHash', type: 'bytes32' },
    ],
  },
] as const
